//Route for submitting Form
POST http://localhost:8000/user/submitForm
content-type: application/json

{
    "name": "qwerty",
    "email": "asd@gmail.com",
    "number": "1234567890",
    "message": "hello"
}
